In [2]:
import os

os.environ["KMP_DUPLICATE_LIB_OK"] = "True"

In [3]:
import torch

In [5]:
torch.version.__version__

'2.7.0+cu118'

In [11]:
a = torch.ones(3, 3)
a

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [12]:
b = torch.ones(3, 3)
b

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [13]:
a + b

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [14]:
a = a.cuda()
a

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

In [15]:
b = b.cuda()
b

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

In [16]:
a + b

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]], device='cuda:0')